spring.datasource.url=jdbc:postgresql://localhost:5432/AssistMe
spring.datasource.username=postgres
spring.datasource.password=your_password_here
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.hikari.maximum-pool-size=10
spring.web.error.include-message=always
spring.web.error.include-stacktrace=always
